
    create table SAMPLE.ADDRESS (
        ID bigint generated by default as identity,
        UUID varchar(255),
        VERSION integer,
        CITY varchar(255),
        STREET varchar(255),
        ZIP_CODE varchar(255),
        COUNTRY varchar(255),
        STATE varchar(255),
        primary key (ID)
    );

    create table SAMPLE.COUNTRY (
        ID varchar(255) not null,
        NAME varchar(255),
        primary key (ID)
    );

    create table SAMPLE.PERSON (
        ID bigint generated by default as identity,
        UUID varchar(255),
        VERSION integer,
        BIRTH_DATE timestamp,
        FIRST_NAME varchar(255),
        LAST_NAME varchar(255),
        SOCIAL_SECURITY_NUMBER varchar(255),
        ADDRESS bigint,
        primary key (ID)
    );

    create table SAMPLE.STATE (
        ID varchar(255) not null,
        NAME varchar(255),
        COUNTRY varchar(255),
        primary key (ID)
    );

    create index IDX_ADDRESS_COUNTRY on SAMPLE.ADDRESS (COUNTRY);

    create index IDX_ADDRESS_STATE on SAMPLE.ADDRESS (STATE);

    alter table SAMPLE.ADDRESS 
        add constraint FK_ADDRESS_STATE 
        foreign key (STATE) 
        references SAMPLE.STATE;

    alter table SAMPLE.ADDRESS 
        add constraint FK_ADDRESS_COUNTRY 
        foreign key (COUNTRY) 
        references SAMPLE.COUNTRY;

    create index IDX_PERSON_LAST_NAME on SAMPLE.PERSON (LAST_NAME);

    create index IDX_PERSON_ADDRESS on SAMPLE.PERSON (ADDRESS);

    alter table SAMPLE.PERSON 
        add constraint FK_PERSON_ADDRESS 
        foreign key (ADDRESS) 
        references SAMPLE.ADDRESS;

    create index IDX_STATE_COUNTRY on SAMPLE.STATE (COUNTRY);

    alter table SAMPLE.STATE 
        add constraint FK_STATE_COUNTRY 
        foreign key (COUNTRY) 
        references SAMPLE.COUNTRY;
