
    create table SAMPLE.COUNTRY (
        ID varchar(255) not null,
        NAME varchar(255),
        primary key (ID)
    );

    create table SAMPLE.PERSON (
        ID bigint generated by default as identity,
        UUID varchar(255),
        VERSION integer,
        BIRTH_DATE timestamp,
        CITY varchar(255),
        FIRST_NAME varchar(255),
        LAST_NAME varchar(255),
        SOCIAL_SECURITY_NUMBER varchar(255),
        STREET varchar(255),
        ZIP_CODE varchar(255),
        COUNTRY varchar(255),
        STATE varchar(255),
        primary key (ID)
    );

    create table SAMPLE.STATE (
        ID varchar(255) not null,
        NAME varchar(255),
        primary key (ID)
    );

    alter table SAMPLE.PERSON 
        add constraint FK_PERSON_STATE 
        foreign key (STATE) 
        references SAMPLE.STATE;

    alter table SAMPLE.PERSON 
        add constraint FK_PERSON_COUNTRY 
        foreign key (COUNTRY) 
        references SAMPLE.COUNTRY;
